### ISSUE TITLE
Unable to return to source from a stream to RCA Inpu

### ISSUE THREAD

**Issue by hawkeyeP** [brianhealey/hacs_amplipi#2]
Once you change a Source to a Stream you are unable to switch back to the RCA Input Source.
The problem is 'RCA Input 0' does not equal 'RCA Input 1'.
I believe the solution is to increment **self._id** by 1.

**Line 177** of media_player.py        
`if f'RCA Input {self._id}' == source:`

Not sure how to submit a correction, so I hope this is helpful.

**Comment by brianhealey** [comment]
Hey, thanks for the input. And you are right. Last minute change broke that feature. :)

Would you mind trying out the latest push?  

Also, you will see that you zones get created now as entities. They will default to `disabled` in HA since the support is evolving, but I would be interested in hearing what works and what doesn't for you.

**Comment by brianhealey** [comment]
Created a separate issue for item 1.

Item 2 is still a WIP, and is not implemented. I am aware of that implementation, however homeassistant has built in join and unjoin functionality that I want to explore before re-implementing that approach.
